### ISSUE TITLE
Broken again after recent upstream commits

### ISSUE THREAD

**Issue by xfzv** [Reledia/glow.yazi#11]
After updating from https://github.com/sxyazi/yazi/commit/35d781e2400de89e6f6012224c3e25b30ee63ebe to https://github.com/sxyazi/yazi/commit/56f9a6a1eb806d81542cd55b2b112a20c012e4c6, `glow.yazi` stopped working. Can reproduce with a minimal config:

```toml
[plugin]
fetchers = [
  { id = "mime", name = "*", run = "mime", if = "!mime", prio = "high" },
]

prepend_previewers = [{ name = "*.md", run = "glow" }]
```

I guess the problematic commit is one of these
- https://github.com/sxyazi/yazi/commit/e8c1d625acb7d35393b6894d290225b2e6c0cf48
- https://github.com/sxyazi/yazi/commit/60cfa7dba975d47da1219257b39ac58a70a1a42d
- https://github.com/sxyazi/yazi/commit/56f9a6a1eb806d81542cd55b2b112a20c012e4c6

Anyone else?
